# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 460)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.refreshButton = QtWidgets.QPushButton(self.centralwidget)
        self.refreshButton.setGeometry(QtCore.QRect(10, 0, 251, 23))
        self.refreshButton.setObjectName("refreshButton")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 30, 251, 351))
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_2.setGeometry(QtCore.QRect(270, 30, 571, 351))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(5)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        self.tableWidget_2.horizontalHeader().setVisible(True)
        self.tableWidget_2.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_2.verticalHeader().setStretchLastSection(False)
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(270, 0, 571, 23))
        self.saveButton.setObjectName("saveButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(910, 0, 47, 13))
        self.label.setObjectName("label")
        self.showSummaryBtn = QtWidgets.QPushButton(self.centralwidget)
        self.showSummaryBtn.setGeometry(QtCore.QRect(850, 30, 141, 41))
        self.showSummaryBtn.setObjectName("showSummaryBtn")
        self.printSummaryBtn = QtWidgets.QPushButton(self.centralwidget)
        self.printSummaryBtn.setGeometry(QtCore.QRect(850, 80, 141, 41))
        self.printSummaryBtn.setObjectName("printSummaryBtn")
        self.showGraphBtn = QtWidgets.QPushButton(self.centralwidget)
        self.showGraphBtn.setGeometry(QtCore.QRect(850, 130, 141, 41))
        self.showGraphBtn.setObjectName("showGraphBtn")
        self.removeEntryButton = QtWidgets.QPushButton(self.centralwidget)
        self.removeEntryButton.setGeometry(QtCore.QRect(850, 180, 141, 41))
        self.removeEntryButton.setObjectName("removeEntryButton")
        self.saveStatisticsButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveStatisticsButton.setGeometry(QtCore.QRect(850, 230, 141, 41))
        self.saveStatisticsButton.setObjectName("saveStatisticsButton")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(10, 390, 251, 23))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.newButton = QtWidgets.QPushButton(self.splitter)
        self.newButton.setObjectName("newButton")
        self.loadButton = QtWidgets.QPushButton(self.splitter)
        self.loadButton.setObjectName("loadButton")
        self.removeButton = QtWidgets.QPushButton(self.splitter)
        self.removeButton.setObjectName("removeButton")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setGeometry(QtCore.QRect(270, 390, 571, 23))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.itemBox = QtWidgets.QComboBox(self.splitter_2)
        self.itemBox.setObjectName("itemBox")
        self.commentField = QtWidgets.QLineEdit(self.splitter_2)
        self.commentField.setObjectName("commentField")
        self.priceFieldEUR = QtWidgets.QLineEdit(self.splitter_2)
        self.priceFieldEUR.setObjectName("priceFieldEUR")
        self.priceFieldCZK = QtWidgets.QLineEdit(self.splitter_2)
        self.priceFieldCZK.setObjectName("priceFieldCZK")
        self.dateEdit = QtWidgets.QDateEdit(self.splitter_2)
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 2, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setMaximumDate(QtCore.QDate(9999, 3, 30))
        self.dateEdit.setDate(QtCore.QDate(2020, 2, 1))
        self.dateEdit.setObjectName("dateEdit")
        self.addButton = QtWidgets.QPushButton(self.splitter_2)
        self.addButton.setObjectName("addButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Finance"))
        self.refreshButton.setText(_translate("MainWindow", "Refresh"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Year"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Month"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Type"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Comment"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Price EUR"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Price CZK"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Date"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
        self.label.setText(_translate("MainWindow", "Tools"))
        self.showSummaryBtn.setText(_translate("MainWindow", "Show summary"))
        self.printSummaryBtn.setText(_translate("MainWindow", "Print summary"))
        self.showGraphBtn.setText(_translate("MainWindow", "Show graph"))
        self.removeEntryButton.setText(_translate("MainWindow", "Remove entry"))
        self.saveStatisticsButton.setText(_translate("MainWindow", "Save statistics"))
        self.newButton.setText(_translate("MainWindow", "New"))
        self.loadButton.setText(_translate("MainWindow", "Load"))
        self.removeButton.setText(_translate("MainWindow", "Remove"))
        self.commentField.setText(_translate("MainWindow", "Comment"))
        self.priceFieldEUR.setText(_translate("MainWindow", "EUR"))
        self.priceFieldCZK.setText(_translate("MainWindow", "CZK"))
        self.addButton.setText(_translate("MainWindow", "Add"))

